# Generated by Django 4.2.16 on 2024-09-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_slug'),
    ]

    operations = [
    ]
